--5-clinique-evolution.sql
CREATE TABLE FACTURES(
    numF INTEGER PRIMARY KEY AUTOINCREMENT,
    numS INTEGER NOT NULL,
    dateF DATE,
    montantF INTEGER,
    payeeF BOOLEAN NOT NULL,
    
    FOREIGN KEY (numS) REFERENCES SOINS(numS) ON DELETE CASCADE
)
;

